spring:
  application:
    name: msvc-users
  profiles:
    active: @activatedProperties@
  flyway:
    baseline-on-migrate: true
    locations:
    - "classpath:db/migration/mysql"
    - "classpath:db/migration/common"