spring:
  # flyway:
  #  enabled: true
  #  validate-on-migrate: true
  #   locations:
  #   - "classpath:db/migration/mysql"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
server:
  port: 8001
logging:
  level:
    org:
      hibernate:
        SQL: debug
msvc:
  courses:
    url: ${COURSES_URL:msvc-courses:8002/courses2}